import '../globals.css';

import { Suspense } from 'react';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { getUsers } from '@/app/postgres/services/getUsers';
import { QueryResultRow } from '@vercel/postgres';

import CreateUserDrizzle from './components/CreateUserDrizzle';
import UserTableDrizzle, {
  SkeletonUserDrizzle,
} from './components/UserTableDrizzle';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <h1>Vercel Postgres with Drizzle</h1>
        <UserTableDrizzle />
        <CreateUserDrizzle />

        {children}
      </body>
    </html>
  );
}
